# Generated by Django 5.1.3 on 2025-01-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminproduct",
            name="category",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="adminproduct",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminproduct",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="adminproduct",
            name="price",
            field=models.TextField(blank=True, null=True),
        ),
    ]
