# Generated by Django 5.1.3 on 2025-01-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_adminproduct_category_adminproduct_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="check_auth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("key", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.adminproduct",
                    ),
                ),
            ],
        ),
    ]
