# Generated by Django 5.1.3 on 2025-01-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_check_auth_checkuser_alter_checkuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkuser",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
