# Generated by Django 5.1.3 on 2025-01-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="image",
            field=models.ImageField(default=1, upload_to="image/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
