# Generated by Django 5.1.3 on 2025-01-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_cart_image_cart_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminproduct",
            name="stock_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cart",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
