# Generated by Django 5.1.3 on 2025-01-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_cart_stock_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="stock_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
