# Generated by Django 5.1.3 on 2025-01-17 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.cart"
            ),
        ),
    ]
