# Generated by Django 5.1.3 on 2025-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_adminproduct_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminproduct",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5
            ),
        ),
    ]
