# Generated by Django 5.1.3 on 2025-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_adminproduct_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usersignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phonenumber", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("pasword", models.CharField(max_length=10)),
                ("confirmpasword", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
