# Generated by Django 5.1.3 on 2025-02-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_usersignup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersignup",
            name="confirmpasword",
        ),
        migrations.AlterField(
            model_name="usersignup",
            name="pasword",
            field=models.TextField(),
        ),
    ]
