# Generated by Django 5.1.3 on 2025-02-05 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_usersignup_confirmpasword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.usersignup",
            ),
            preserve_default=False,
        ),
    ]
