# Generated by Django 5.1.3 on 2025-02-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_cart_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Useradress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("phonenumber", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("pincode", models.IntegerField()),
                ("city", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.usersignup"
                    ),
                ),
            ],
        ),
    ]
