# Generated by Django 5.1.3 on 2025-02-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_useradress"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradress",
            name="addreass",
            field=models.TextField(blank=True),
        ),
    ]
