# Generated by Django 5.1.3 on 2025-02-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_useradress_addreass"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminproduct",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
