# Generated by Django 5.1.3 on 2025-02-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_adminproduct_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=255, null=True)),
                ("lastname", models.CharField(blank=True, max_length=255, null=True)),
                ("phonenumber", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True)),
            ],
        ),
    ]
