# Generated by Django 5.1.3 on 2025-03-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="totalprice",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
