# Generated by Django 5.1.3 on 2025-03-04 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_cart_price_alter_cart_totalprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(blank=True, null=True)),
                ("totalprice", models.FloatField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=1)),
                ("is_coupen", models.BooleanField(default=False)),
                ("coupen_code", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "adreass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.contactdetails",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.adminproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.usersignup"
                    ),
                ),
            ],
        ),
    ]
