# Generated by Django 5.1.3 on 2025-03-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_buyproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyproduct",
            name="is_orderConfirm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="buyproduct",
            name="paymentmethod",
            field=models.TextField(blank=True, null=True),
        ),
    ]
