# Generated by Django 5.1.3 on 2025-03-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_buyproduct_is_orderconfirm_buyproduct_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyproduct",
            name="order_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buyproduct",
            name="payment_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
