# Generated by Django 5.1.3 on 2025-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_buyproduct_order_id_buyproduct_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyproduct",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
