# Generated by Django 5.1.3 on 2025-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_buyproduct_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyproduct",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
