# Generated by Django 5.1.3 on 2025-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CoupenName", models.TextField(blank=True, null=True)),
                ("discount", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
