# Generated by Django 5.1.3 on 2025-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_coupen"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyproduct",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="buyproduct",
            name="discountedamount",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
