# Generated by Django 5.1.3 on 2025-03-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_buyproduct_discount_buyproduct_discountedamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupen",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
