# Generated by Django 5.1.3 on 2025-04-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_coupen_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyproduct",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
    ]
