# Generated by Django 5.1.3 on 2025-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_buyproduct_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyproduct",
            name="status",
            field=models.TextField(blank=True, default="ordered", null=True),
        ),
    ]
