# Generated by Django 5.1.3 on 2025-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_alter_buyproduct_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="coupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="buyproduct",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
