# Generated by Django 5.1.3 on 2025-04-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_reviewpage_delete_coupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewpage",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
