# Generated by Django 5.1.3 on 2025-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_reviewpage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersignup",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
